language: rust
os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

cache: cargo
matrix:
  include:
    - name: Linux Binary
      env: TARGET=x86_64-unknown-linux-musl
      rust: stable
      before_script: rustup target add $TARGET
      script: cargo build --release --target $TARGET --locked
      addons:
        apt:
          packages:
            - musl-tools

    - name: macOS Binary
      env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
      os: osx
      rust: stable
      script: cargo build --release --target $TARGET --locked
      install: true